// Country list with emoji flags used for member profiles.
// `name` is what we persist in the members.country column; `flag` is shown in the UI.
export const COUNTRY_FLAGS = [
  { name: 'Cameroon', flag: '🇨🇲' },
  { name: 'Rwanda', flag: '🇷🇼' },
  { name: 'Uganda', flag: '🇺🇬' },
  { name: 'Kenya', flag: '🇰🇪' },
  { name: 'Tanzania', flag: '🇹🇿' },
  { name: 'Nigeria', flag: '🇳🇬' },
  { name: 'Ghana', flag: '🇬🇭' },
  { name: 'South Africa', flag: '🇿🇦' },
  { name: 'Ethiopia', flag: '🇪🇹' },
  { name: 'Egypt', flag: '🇪🇬' },
  { name: 'Morocco', flag: '🇲🇦' },
  { name: 'Algeria', flag: '🇩🇿' },
  { name: 'Tunisia', flag: '🇹🇳' },
  { name: 'Senegal', flag: '🇸🇳' },
  { name: "Côte d'Ivoire", flag: '🇨🇮' },
  { name: 'Democratic Republic of the Congo', flag: '🇨🇩' },
  { name: 'Republic of the Congo', flag: '🇨🇬' },
  { name: 'Gabon', flag: '🇬🇦' },
  { name: 'Chad', flag: '🇹🇩' },
  { name: 'Central African Republic', flag: '🇨🇫' },
  { name: 'Equatorial Guinea', flag: '🇬🇶' },
  { name: 'Angola', flag: '🇦🇴' },
  { name: 'Zambia', flag: '🇿🇲' },
  { name: 'Zimbabwe', flag: '🇿🇼' },
  { name: 'Mozambique', flag: '🇲🇿' },
  { name: 'Botswana', flag: '🇧🇼' },
  { name: 'Namibia', flag: '🇳🇦' },
  { name: 'Burundi', flag: '🇧🇮' },
  { name: 'Malawi', flag: '🇲🇼' },
  { name: 'Mali', flag: '🇲🇱' },
  { name: 'Burkina Faso', flag: '🇧🇫' },
  { name: 'Niger', flag: '🇳🇪' },
  { name: 'Guinea', flag: '🇬🇳' },
  { name: 'Benin', flag: '🇧🇯' },
  { name: 'Togo', flag: '🇹🇬' },
  { name: 'Sierra Leone', flag: '🇸🇱' },
  { name: 'Liberia', flag: '🇱🇷' },
  { name: 'Sudan', flag: '🇸🇩' },
  { name: 'South Sudan', flag: '🇸🇸' },
  { name: 'Somalia', flag: '🇸🇴' },
  { name: 'Libya', flag: '🇱🇾' },
  { name: 'United States', flag: '🇺🇸' },
  { name: 'Canada', flag: '🇨🇦' },
  { name: 'United Kingdom', flag: '🇬🇧' },
  { name: 'Ireland', flag: '🇮🇪' },
  { name: 'France', flag: '🇫🇷' },
  { name: 'Germany', flag: '🇩🇪' },
  { name: 'Spain', flag: '🇪🇸' },
  { name: 'Portugal', flag: '🇵🇹' },
  { name: 'Italy', flag: '🇮🇹' },
  { name: 'Netherlands', flag: '🇳🇱' },
  { name: 'Belgium', flag: '🇧🇪' },
  { name: 'Switzerland', flag: '🇨🇭' },
  { name: 'Sweden', flag: '🇸🇪' },
  { name: 'Norway', flag: '🇳🇴' },
  { name: 'Denmark', flag: '🇩🇰' },
  { name: 'Finland', flag: '🇫🇮' },
  { name: 'Poland', flag: '🇵🇱' },
  { name: 'Russia', flag: '🇷🇺' },
  { name: 'Turkey', flag: '🇹🇷' },
  { name: 'United Arab Emirates', flag: '🇦🇪' },
  { name: 'Saudi Arabia', flag: '🇸🇦' },
  { name: 'Qatar', flag: '🇶🇦' },
  { name: 'India', flag: '🇮🇳' },
  { name: 'Pakistan', flag: '🇵🇰' },
  { name: 'China', flag: '🇨🇳' },
  { name: 'Japan', flag: '🇯🇵' },
  { name: 'South Korea', flag: '🇰🇷' },
  { name: 'Indonesia', flag: '🇮🇩' },
  { name: 'Malaysia', flag: '🇲🇾' },
  { name: 'Singapore', flag: '🇸🇬' },
  { name: 'Philippines', flag: '🇵🇭' },
  { name: 'Australia', flag: '🇦🇺' },
  { name: 'New Zealand', flag: '🇳🇿' },
  { name: 'Brazil', flag: '🇧🇷' },
  { name: 'Argentina', flag: '🇦🇷' },
  { name: 'Mexico', flag: '🇲🇽' },
];

const FLAG_BY_NAME = COUNTRY_FLAGS.reduce((acc, c) => {
  acc[c.name.toLowerCase()] = c.flag;
  return acc;
}, {});

export const getFlagByCountry = (name) => {
  if (!name) return '';
  return FLAG_BY_NAME[String(name).trim().toLowerCase()] || '';
};
