<!DOCTYPE html>
<html>
<head><meta charset="utf-8"><style>
body{font-family:DejaVu Sans,sans-serif;font-size:12px}
.header{text-align:center;font-weight:bold;margin-bottom:12px}
table{border-collapse:collapse;width:100%}
td,th{border:1px solid #ccc;padding:8px;text-align:left}
.amount{font-size:18px;font-weight:bold}
</style></head>
<body>
<div class="header">{{ $general_setting->site_title ?? 'Beyond Enterprise' }}</div>
<h2>Labour Payment Receipt</h2>
<table>
<tr><th>Reference</th><td>{{ $payment->reference_no }}</td></tr>
<tr><th>Event</th><td>{{ $payment->event->name }} ({{ $payment->event->reference_no }})</td></tr>
<tr><th>Worker</th><td>{{ $payment->workerProfile->displayName() }}</td></tr>
<tr><th>Role</th><td>{{ optional($payment->assignment)->assignment_role }}</td></tr>
<tr><th>Amount</th><td class="amount">{{ number_format($payment->amount) }} XAF</td></tr>
<tr><th>Method</th><td>{{ $payment->payment_method }}</td></tr>
<tr><th>Paid at</th><td>{{ optional($payment->paid_at)->format('d M Y H:i') ?? 'Pending' }}</td></tr>
</table>
@if($payment->notes)<p><strong>Notes:</strong> {{ $payment->notes }}</p>@endif
<p style="margin-top:24px;font-size:10px;color:#666">Generated by Beyond Enterprise Events.</p>
</body>
</html>
